const eventlist = [
  {
    title: "Robowars",
    date: "Mar 14th, 2024",
    location: "TBD",
    eventType: "Competition",
    time: "9:00-17:00",
    description:
      "Robowars is a competitive robotic event that invites passionate and enthusiastic participants from all over Montreal and beyond to showcase their engineering skills.",
    Price: "TBD",
    organizer: "Ardalan Jamshidi",
    sponsors: "TBD",
    image: "Robowars.webp",
    link: "robowars",
  },
  {
    title: "Warhacks",
    date: "Feb 18th, 2024",
    location: "TBD",
    eventType: "Competition",
    time: "TBD",
    description:
      "Warhacks is a one-day event designed to introduce you to the world of hardware hackathon. Come spend the day with us, and you will get to build your robot from scratch.",
    price: "TBD",
    organizer: "Minh Huynh",
    sponsors: "TBD",
    image: "Warhacks.webp",
    link: "warhacks",
  },

  {
    title: "Intro to Lab Equipements",
    date: "Sep 14th, 2023",
    location: "B-Annex 204",
    eventType: "PASSED",
    time: "18:00-21:00",
    description:
      "Boost your electrical engineering knowledge with our tutorial tailored to ELEC 273 and ELEC 311, and excel in your coursework.",
    Price: "$10 CAD",
    organizer: "Alexandre Fontaine",
    sponsors: "TBD",
    image: "Intro-to-lab-equipement.webp",
    link: "intro-to-lab-equipement",
  },

  {
    title: "IEEE Day",
    date: "Oct 3rd, 2023",
    location: "TBD",
    eventType: "PASSED",
    time: "TBD",
    description:
      "IEEE Day is an annual celebration of IEEE around the world that recognizes and acknowledges the dedication and vision of IEEE.",
    Price: "TBD",
    organizer: "Shami Ivan Senga",
    sponsors: "TBD",
    image: "IEEE-Day.webp",
    link: "ieee-day",
  },
  {
    title: "Intro to Matlab",
    date: "Oct 5th, 2023",
    location: "MB - S1.435",
    eventType: "PASSED",
    time: "18:00-20:00",
    description:
      "Unlock MATLAB's potential in our interactive workshop! Learn the basics, from navigating the interface to data visualization, with giveaways and free refreshments. Perfect for students or anyone curious about MATLAB.",
    Price: "TBD",
    organizer: "Ngoc Son (Samuel) Tran",
    sponsors: "TBD",
    image: "Intro-to-Matlab.webp",
    link: "intro-to-matlab",
  },
  {
    title: "Soldering Tutorial",
    date: "Oct 19th, 2023",
    location: "MB - 3.255",
    eventType: "PASSED",
    time: "14:00-16:00",
    description:
      "Explore the fundamentals of soldering with our easy-to-follow tutorial. Learn how to create secure connections for various applications.",
    Price: "TBD",
    organizer: "Alexandre Fontaine",
    sponsors: "TBD",
    image: "Intro-to-Soldering.webp",
    link: "soldering-tutorial",
  },
  {
    title: "3D Modeling and Design P2",
    date: "Oct 26th, 2023",
    location: "MB - 3.255",
    eventType: "PASSED",
    time: "18:00-21:00",
    description:
      "Embark on a journey to master 3D modeling in our beginner's workshop and learn the skill used by designers, engineers, and artists worldwide",
    Price: "TBD",
    organizer: "Alexandre Fontaine",
    sponsors: "TBD",
    image: "3D-Modeling-and-Design.webp",
    link: "3d-modeling-and-design",
  },
  {
    title: "IEEEXtreme",
    date: "Oct 28th, 2023",
    location: "TBD",
    eventType: "PASSED",
    time: "TBD",
    description:
      "IEEEXtreme is a global 24-hour marathon during which teams of three or four programmers are given a set of programming questions to solve.",
    Price: "TBD",
    organizer: "Ardalan Jamshidi",
    sponsors: "TBD",
    image: "IEEEXtreme.webp",
    link: "ieeextreme",
  },
  {
    title: "Intro to Material Selection",
    date: "Nov 9th, 2023",
    location: "H-529",
    eventType: "PASSED",
    time: "18h-21h",
    description:
      "Learn how to select the right material for your project and how to use it properly.",
    Price: "Free",
    organizer: "Alexandre Fontaine",
    sponsors: "TBD",
    image: "Intro-to-material-selection.png",
    link: "intro-to-material-selection",
  },
  {
    title: "Robowars Info Session",
    date: "Nov 15th, 2023",
    location: "H-655.02",
    eventType: "PASSED",
    time: "12h-13h",
    description:
      "Learn more about Robowars, the biggest robotics competition in Montreal! ",
    Price: "Free",
    organizer: "Ardalan Jamshidi",
    sponsors: "TBD",
    image: "robowars-info-session.webp",
    link: "robowars-info-session",
  },
  {
    title: "Intro to Microcontrollers",
    date: "Nov 23rd, 2023",
    location: "H-537",
    eventType: "PASSED",
    time: "18h-21h",
    description:
      "Discover the magic of microcontrollers in our beginner-friendly workshop! Unleash your creativity and bring your electronic projects to life.",
    Price: "20$ CAD",
    organizer: "Alexandre Fontaine",
    sponsors: "TBD",
    image: "Intro-to-Microcontrollers.webp",
    link: "intro-to-microcontrollers",
  },
];

export default eventlist;
