const eventlist = [
  {
    Title: "Intro to Arduino",
    Date: "Nov 9th, 2023",
    Location: "H-620",
    Type: "Academic",
    Time: "TBD",
    Description:
      "Learn Arduino fundamentals and gain hands-on experience. Explore the microcontroller's vast applications and immediately apply your knowledge with guidance from experienced tutors.",
    Price: "TBD",
    Organizer: "Alexandre Fontaine",
    Sponsors: "TBD",
    Image: "Intro-to-Arduino.png",
    link: "intro-to-arduino",
  },
  {
    Title: "Intro to Transistors",
    Date: "Nov 16th, 2023",
    Location: "H-529",
    Type: "Academic",
    Time: "18h-21h",
    Description:
      "Reinforce your theoretical knowledge about transistors by building and experimenting with actual electric circuits.",
    Price: "10",
    Organizer: "Alexandre Fontaine",
    Sponsors: "",
    Image: "Intro-to-Transistors.png",
    link: "intro-to-transistors",
  },
  {
    Title: "Robowars",
    Date: "Mar 14th, 2024",
    Location: "TBD",
    Type: "Competition",
    Time: "9:00-17:00",
    Description:
      "Robowars is a competitive robotic event that invites passionate and enthusiastic participants from all over Montreal and beyond to showcase their engineering skills.",
    Price: "TBD",
    Organizer: "Ardalan Jamshidi",
    Sponsors: "TBD",
    Image: "Robowars.png",
    link: "robowars",
  },
  {
    Title: "Warhacks",
    Date: "Feb 18th, 2024",
    Location: "TBD",
    Type: "Competition",
    Time: "TBD",
    Description:
      "Warhacks is a one-day event designed to introduce you to the world of hardware hackathon. Come spend the day with us, and you will get to build your robot from scratch.",
    price: "TBD",
    Organizer: "Minh Huynh",
    Sponsors: "TBD",
    Image: "Warhacks.png",
    link: "warhacks",
  },

  {
    Title: "Intro to Lab Equipements",
    Date: "Sep 14th, 2023",
    Location: "B-Annex 204",
    Type: "PASSED",
    Time: "18:00-21:00",
    Description:
      "Boost your electrical engineering knowledge with our tutorial tailored to ELEC 273 and ELEC 311, and excel in your coursework.",
    Price: "$10 CAD",
    Organizer: "Alexandre Fontaine",
    Sponsors: "TBD",
    Image: "Intro-to-lab-equipement.png",
    link: "intro-to-lab-equipement",
  },

  {
    Title: "IEEE Day",
    Date: "Oct 3rd, 2023",
    Location: "TBD",
    Type: "PASSED",
    Time: "TBD",
    Description:
      "IEEE Day is an annual celebration of IEEE around the world that recognizes and acknowledges the dedication and vision of IEEE.",
    Price: "TBD",
    Organizer: "Shami Ivan Senga",
    Sponsors: "TBD",
    Image: "IEEE-Day.png",
    link: "ieee-day",
  },
  {
    Title: "Intro to Matlab",
    Date: "Oct 5th, 2023",
    Location: "MB - S1.435",
    Type: "PASSED",
    Time: "18:00-20:00",
    Description:
      "Unlock MATLAB's potential in our interactive workshop! Learn the basics, from navigating the interface to data visualization, with giveaways and free refreshments. Perfect for students or anyone curious about MATLAB.",
    Price: "TBD",
    Organizer: "Ngoc Son (Samuel) Tran",
    Sponsors: "TBD",
    Image: "Intro-to-Matlab.png",
    link: "intro-to-matlab",
  },
  {
    Title: "Soldering Tutorial",
    Date: "Oct 19th, 2023",
    Location: "MB - 3.255",
    Type: "PASSED",
    Time: "14:00-16:00",
    Description:
      "Explore the fundamentals of soldering with our easy-to-follow tutorial. Learn how to create secure connections for various applications.",
    Price: "TBD",
    Organizer: "Alexandre Fontaine",
    Sponsors: "TBD",
    Image: "Intro-to-Soldering.png",
    link: "soldering-tutorial",
  },
  {
    Title: "3D Modeling and Design P2",
    Date: "Oct 26th, 2023",
    Location: "MB - 3.255",
    Type: "PASSED",
    Time: "18:00-21:00",
    Description:
      "Embark on a journey to master 3D modeling in our beginner's workshop and learn the skill used by designers, engineers, and artists worldwide",
    Price: "TBD",
    Organizer: "Alexandre Fontaine",
    Sponsors: "TBD",
    Image: "3D-Modeling-and-Design.png",
    link: "3d-modeling-and-design",
  },
  {
    Title: "IEEEXtreme",
    Date: "Oct 28th, 2023",
    Location: "TBD",
    Type: "PASSED",
    Time: "TBD",
    Description:
      "IEEEXtreme is a global 24-hour marathon during which teams of three or four programmers are given a set of programming questions to solve.",
    Price: "TBD",
    Organizer: "Ardalan Jamshidi",
    Sponsors: "TBD",
    Image: "IEEEXtreme.png",
    link: "ieeextreme",
  },
];

export default eventlist;
