const execTeam = [
  {
    firstName: "Shami Ivan",
    lastName: "Senga",
    position: "Branch Chair",
    program: "B.Eng. Coen.",
    discord: "cmumind#8981",
    emailIEEE: "chair@ieeeconcordia.ca",
    linkedIn: "",
    image: "Ivan.webp",
  },
  {
    firstName: "Yara",
    lastName: "Stouhi",
    position: "Branch Treasurer",
    program: "B.Eng. Coen.",
    discord: "yara#4460",
    emailIEEE: "treasurer@ieeeconcordia.ca",
    linkedIn: "",
    image: "Yara.webp",
  },
  {
    firstName: "Kartik",
    lastName: "Teotia",
    position: "Branch Vice-Chair",
    program: "B.Eng. Elec.",
    discord: "Kartik T#7583",
    emailIEEE: "vicechair@ieeeconcordia.ca",
    linkedIn: "",
    image: "Kartik.webp",
  },
  {
    firstName: "Sabine",
    lastName: "Hleiss",
    position: "Branch Secretary",
    program: "",
    discord: "sabine#6480",
    emailIEEE: "secretary@ieeeconcordia.ca",
    linkedIn: "",
    image: "Sabine.webp",
  },
  {
    firstName: "Achal",
    lastName: "Patel",
    position: "Branch Marketing",
    program: "B.Eng. Coen.",
    discord: "zwaky#7372",
    emailIEEE: "academics@ieeeconcordia.ca",
    linkedIn: "",
    image: "Achal.webp",
  },
  {
    firstName: "Alexandre",
    lastName: "Fontaine",
    position: "Branch Academics",
    program: "B.Eng. Elec.",
    discord: "zwaky#7372",
    emailIEEE: "academics@ieeeconcordia.ca",
    linkedIn: "",
    image: "Alex.webp",
  },
  {
    firstName: "Rayan",
    lastName: "Alkayal",
    position: "Director of IT",
    program: "",
    discord: "itsrhino_",
    emailIEEE: "itdirector@ieeeconcordia.ca",
    linkedIn: "",
    image: "Rayan.webp",
  },
  {
    firstName: "Juan",
    lastName: "Vergas",
    position: "Director of IT",
    program: "",
    discord: "sum_re1",
    emailIEEE: "itdirector@ieeeconcordia.ca",
    linkedIn: "",
    image: "Juan.webp",
  },
  {
    firstName: "Houssam Eddine",
    lastName: "Righi",
    position: "Branch Webmaster",
    program: "B.Eng. Soen.",
    discord: "hoorii",
    emailIEEE: "webmaster@ieeeconcordia.ca",
    linkedIn: "",
    image: "Houssam.webp",
  },
  {
    firstName: "Ardalan",
    lastName: "Jamshidi",
    position: "Director of Competitions",
    program: "B.Eng. Coen.",
    discord: "ardianapolis#7436",
    emailIEEE: "competitions@ieeeconcordia.ca",
    linkedIn: "",
    image: "Ardalan.webp",
  },
  {
    firstName: "Mathias",
    lastName: "Desrochers",
    position: "Director of Lab Services",
    program: "B.Eng. Elec.",
    discord: "M3thRocks#6275",
    emailIEEE: "services@ieeeconcordia.ca",
    linkedIn: "",
    image: "Mathias.webp",
  },
  {
    firstName: "Kaden Perelmiter",
    lastName: "",
    position: "Director of Lab Services",
    program: "B.Eng. Elec.",
    discord: "M3thRocks#6275",
    emailIEEE: "services@ieeeconcordia.ca",
    linkedIn: "",
    image: "Kaden.webp",
  },
  {
    firstName: "Minh",
    lastName: "Huynh",
    position: "Director of Warhacks",
    program: "",
    discord: "saucy0662",
    emailIEEE: "warhacks@ieeeconcordia.ca",
    linkedIn: "",
    image: "Minh.webp",
  },
  {
    firstName: "Mazen",
    lastName: "Mohamed",
    position: "Director of Projects",
    program: "",
    discord: "_.mazen._",
    emailIEEE: "projects@ieeeconcordia.ca",
    linkedIn: "",
    image: "Mazen.webp",
  },
  {
    firstName: "Rahil",
    lastName: "Kaddad",
    position: "Director of External",
    program: "B.Eng Elec",
    discord: "rahilkakkad",
    emailIEEE: "external@ieeeconcordia.ca",
    linkedIn: "",
    image: "",
  },
  {
    firstName: "Rahil",
    lastName: "Kaddad",
    position: "Director of External",
    program: "B.Eng Elec",
    discord: "rahilkakkad",
    emailIEEE: "external@ieeeconcordia.ca",
    linkedIn: "",
    image: "",
  },
];
